baseURL = 'https://example.org/'

# Metadata
languageCode = 'en-us'
theme = 'hugo-bearblog'
title = "My Blog"
author = "Andrea Grillo"
copyright = "Copyright Â© 2026, Andrea Grillo."

# SEO
enableRobotsTXT = true

# Links
disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]

[permalinks]
  blog = "/:slug/"
  tags = "/blog/:slug"

[params]
  description = "Made with :heart: in Milan"

  # favicon = "images/favicon.png"

  enablePostNavigator = true

  # Social links
  [[params.socialLinks]]
    name = "GitHub"
    url = "https://github.com/krusty93"
  
  [[params.socialLinks]]
    name = "LinkedIn"
    url = "https://linkedin.com/in/grillo-andrea"
  
  [[params.socialLinks]]
    name = "RSS"
    url = "/feed/"
  
  [[params.socialLinks]]
    name = "InfoQ"
    url = "https://www.infoq.com/profile/Andrea-Grillo/#articles"

# https://gohugo.io/configuration/markup/#highlight
[markup]
  [markup.highlight]
    style = 'friendly'
    lineNos = true
    lineNumbersInTable = false
    codeFences = true

[params.giscus]
  repo = "krusty93/personal-blog"
  repoID = "R_kgDORA05qA"
  category = "Announcements"
  categoryID = "DIC_kwDORA05qM4C1Zuv"
  mapping = "url"
  strict = "0"
  reactionsEnabled = "1"
  emitMetadata = "1"
  inputPosition = "bottom"
  theme = "preferred_color_scheme"
  lang = "en"
  loading = "lazy"
  crossorigin = "anonymous"

[outputs]
  home = ['html', 'rss']
  section = ['html', 'rss']
  taxonomy = ['html']
  term = ['html']

[outputFormats]
  [outputFormats.RSS]
    mediatype = "application/rss"
    baseName = "feed"